name: K8s_deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get aws-iam-authenticator, set Kubeconfig, and deploy to EKS
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
        aws-iam-authenticator help     
        echo ${KUBE_CONFIG_DATA} | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
        # Deploy pods
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/admin_frontend_deploy.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/cart_db_deploy.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/cart_microservice_deploy.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/orders_db_deploy.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/orders_microservice_deploy.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/product_db_deploy.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/product_microservice_deploy.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/web_frontend_deploy.yaml
        # Deploy services
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/admin_frontend_service.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/cart_db_service.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/cart_microservice_service.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/orders_db_service.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/orders_microservice_service.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/product_db_service.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/product_microservice_service.yaml
        kubectl apply -f  https://raw.githubusercontent.com/k8tan/frothly_store/master/deploy/kubernetes/web_frontend_service.yaml
